version: '3.8'

services:
  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: news_application_db
      MYSQL_USER: news_user
      MYSQL_PASSWORD: news_password
    volumes:
      - mariadb_data:/var/lib/mysql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=news_application_db
      - DB_USER=news_user
      - DB_PASSWORD=news_password

volumes:
  mariadb_data:
